"""Add model_used to formulations; backfill proposed rows with claude-opus-4-7

Revision ID: 0006_add_model_used
Revises: 0005_seed_demo_data
Create Date: 2026-04-26
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0006_add_model_used"
down_revision = "0005_seed_demo_data"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("formulations", sa.Column("model_used", sa.String(128), nullable=True))

    # Backfill all existing proposed formulations — they were generated by the seed
    # which represents Claude Opus 4.7 proposals.
    op.execute(
        sa.text(
            "UPDATE formulations SET model_used = 'claude-opus-4-7' WHERE kind = 'proposed'"
        )
    )


def downgrade() -> None:
    op.drop_column("formulations", "model_used")
